USE [master]
GO

-- Verify that the stored procedure does not already exist.  
IF OBJECT_ID ( 'usp_GetErrorInfo', 'P' ) IS NOT NULL   
    DROP PROCEDURE usp_GetErrorInfo;  
GO  
  
-- Create procedure to retrieve error information.  
CREATE PROCEDURE usp_GetErrorInfo  
AS  
--系統拋回訊息用
	DECLARE @ErrorMessage As VARCHAR(1000) = CHAR(10)+'Error Code:' +CAST(ERROR_NUMBER() AS VARCHAR)
											+CHAR(10)+'Error Message:'+	ERROR_MESSAGE()
											+CHAR(10)+'Error Line:'+	CAST(ERROR_LINE() AS VARCHAR)
	DECLARE @ErrorSeverity As Numeric = ERROR_SEVERITY()
	DECLARE @ErrorState As Numeric = ERROR_STATE()
	RAISERROR( @ErrorMessage, @ErrorSeverity, @ErrorState);--回傳錯誤資訊
GO  

BEGIN TRY

/****** Object:  Database [DigiChamber]    Script Date: 2019/10/17 上午 01:18:17 ******/
CREATE DATABASE [DigiChamber]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DigiChamber', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\DigiChamber.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DigiChamber_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\DigiChamber_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )


IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DigiChamber].[dbo].[sp_fulltext_database] @action = 'enable'
end


ALTER DATABASE [DigiChamber] SET ANSI_NULL_DEFAULT OFF 


ALTER DATABASE [DigiChamber] SET ANSI_NULLS OFF 


ALTER DATABASE [DigiChamber] SET ANSI_PADDING OFF 


ALTER DATABASE [DigiChamber] SET ANSI_WARNINGS OFF 


ALTER DATABASE [DigiChamber] SET ARITHABORT OFF 


ALTER DATABASE [DigiChamber] SET AUTO_CLOSE OFF 


ALTER DATABASE [DigiChamber] SET AUTO_SHRINK OFF 


ALTER DATABASE [DigiChamber] SET AUTO_UPDATE_STATISTICS ON 


ALTER DATABASE [DigiChamber] SET CURSOR_CLOSE_ON_COMMIT OFF 


ALTER DATABASE [DigiChamber] SET CURSOR_DEFAULT  GLOBAL 


ALTER DATABASE [DigiChamber] SET CONCAT_NULL_YIELDS_NULL OFF 


ALTER DATABASE [DigiChamber] SET NUMERIC_ROUNDABORT OFF 


ALTER DATABASE [DigiChamber] SET QUOTED_IDENTIFIER OFF 


ALTER DATABASE [DigiChamber] SET RECURSIVE_TRIGGERS OFF 


ALTER DATABASE [DigiChamber] SET  DISABLE_BROKER 


ALTER DATABASE [DigiChamber] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 


ALTER DATABASE [DigiChamber] SET DATE_CORRELATION_OPTIMIZATION OFF 


ALTER DATABASE [DigiChamber] SET TRUSTWORTHY OFF 


ALTER DATABASE [DigiChamber] SET ALLOW_SNAPSHOT_ISOLATION OFF 


ALTER DATABASE [DigiChamber] SET PARAMETERIZATION SIMPLE 


ALTER DATABASE [DigiChamber] SET READ_COMMITTED_SNAPSHOT OFF 


ALTER DATABASE [DigiChamber] SET HONOR_BROKER_PRIORITY OFF 


ALTER DATABASE [DigiChamber] SET RECOVERY SIMPLE 


ALTER DATABASE [DigiChamber] SET  MULTI_USER 


ALTER DATABASE [DigiChamber] SET PAGE_VERIFY CHECKSUM  


ALTER DATABASE [DigiChamber] SET DB_CHAINING OFF 


ALTER DATABASE [DigiChamber] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 


ALTER DATABASE [DigiChamber] SET TARGET_RECOVERY_TIME = 60 SECONDS 


ALTER DATABASE [DigiChamber] SET DELAYED_DURABILITY = DISABLED 


ALTER DATABASE [DigiChamber] SET  READ_WRITE 


END TRY

BEGIN CATCH
EXECUTE usp_GetErrorInfo;  
END CATCH
GO